/soc/oplus,pps_charge/oplus,pps_full_normal_sw_vbat_third 0x1208
/soc/oplus,pps_charge/oplus,pps_full_normal_hw_vbat 0x1208
/soc/oplus,pps_charge/oplus,pps_full_normal_sw_vbat 0x1208
/soc/oplus,pps_charge/oplus,curr_max_ma 0x1a90
/soc/oplus,pps_charge/oplus,pps_charge_strategy_temp 0x37 0x37 0x82 0xaa 0x168 0x1c2 0x208
/soc/oplus,pps_charge/oplus,pps_over_high_or_low_current 0x1a90
/soc/oplus,pps_charge/oplus,pps_ibat_over_third 0x2710
